package player;

/**
* player/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from player.idl
* Thursday, 21 May 2015 16:32:51 o'clock KST
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public player.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (player.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = player.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    player.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return player.PlayerHelper.type ();
  }

}
