package player;


/**
* player/PlayerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from player.idl
* Thursday, 21 May 2015 16:32:51 o'clock KST
*/

public abstract class PlayerPOA extends org.omg.PortableServer.Servant
 implements player.PlayerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getPlayer", new java.lang.Integer (0));
    _methods.put ("deletePlayer", new java.lang.Integer (1));
    _methods.put ("updatePlayer", new java.lang.Integer (2));
    _methods.put ("createPlayer", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // player/Player/getPlayer
       {
         try {
           int phone = in.read_long ();
           player.PlayerInfo $result = null;
           $result = this.getPlayer (phone);
           out = $rh.createReply();
           player.PlayerInfoHelper.write (out, $result);
         } catch (player.SQLError $ex) {
           out = $rh.createExceptionReply ();
           player.SQLErrorHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // player/Player/deletePlayer
       {
         try {
           int phone = in.read_long ();
           player.PlayerInfo $result = null;
           $result = this.deletePlayer (phone);
           out = $rh.createReply();
           player.PlayerInfoHelper.write (out, $result);
         } catch (player.SQLError $ex) {
           out = $rh.createExceptionReply ();
           player.SQLErrorHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // player/Player/updatePlayer
       {
         try {
           String name = in.read_wstring ();
           int phone = in.read_long ();
           String password = in.read_wstring ();
           int calory_burned_total = in.read_long ();
           int steps_taken = in.read_long ();
           int exp = in.read_long ();
           int weight = in.read_long ();
           int monster_money = in.read_long ();
           String email = in.read_wstring ();
           player.PlayerInfo $result = null;
           $result = this.updatePlayer (name, phone, password, calory_burned_total, steps_taken, exp, weight, monster_money, email);
           out = $rh.createReply();
           player.PlayerInfoHelper.write (out, $result);
         } catch (player.SQLError $ex) {
           out = $rh.createExceptionReply ();
           player.SQLErrorHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // player/Player/createPlayer
       {
         String name = in.read_wstring ();
         int phone = in.read_long ();
         String password = in.read_wstring ();
         int calory_burned_total = in.read_long ();
         int steps_taken = in.read_long ();
         int exp = in.read_long ();
         int weight = in.read_long ();
         int monster_money = in.read_long ();
         String email = in.read_wstring ();
         player.PlayerInfo $result = null;
         $result = this.createPlayer (name, phone, password, calory_burned_total, steps_taken, exp, weight, monster_money, email);
         out = $rh.createReply();
         player.PlayerInfoHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:player/Player:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Player _this() 
  {
    return PlayerHelper.narrow(
    super._this_object());
  }

  public Player _this(org.omg.CORBA.ORB orb) 
  {
    return PlayerHelper.narrow(
    super._this_object(orb));
  }


} // class PlayerPOA
