package player;

/**
* player/PlayerInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from player.idl
* Thursday, 21 May 2015 16:32:51 o'clock KST
*/

public final class PlayerInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public player.PlayerInfo value = null;

  public PlayerInfoHolder ()
  {
  }

  public PlayerInfoHolder (player.PlayerInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = player.PlayerInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    player.PlayerInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return player.PlayerInfoHelper.type ();
  }

}
