package player;


/**
* player/PlayerInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from player.idl
* Thursday, 21 May 2015 16:32:51 o'clock KST
*/

public final class PlayerInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String password = null;
  public int phone = (int)0;
  public int calory_burned_total = (int)0;
  public int steps_taken = (int)0;
  public int exp = (int)0;
  public int weight = (int)0;
  public int monster_money = (int)0;
  public String email = null;

  public PlayerInfo ()
  {
  } // ctor

  public PlayerInfo (String _name, String _password, int _phone, int _calory_burned_total, int _steps_taken, int _exp, int _weight, int _monster_money, String _email)
  {
    name = _name;
    password = _password;
    phone = _phone;
    calory_burned_total = _calory_burned_total;
    steps_taken = _steps_taken;
    exp = _exp;
    weight = _weight;
    monster_money = _monster_money;
    email = _email;
  } // ctor

} // class PlayerInfo
