package player;


/**
* player/PlayerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from player.idl
* Thursday, 21 May 2015 16:32:51 o'clock KST
*/

public interface PlayerOperations 
{
  player.PlayerInfo getPlayer (int phone) throws player.SQLError;
  player.PlayerInfo deletePlayer (int phone) throws player.SQLError;
  player.PlayerInfo updatePlayer (String name, int phone, String password, int calory_burned_total, int steps_taken, int exp, int weight, int monster_money, String email) throws player.SQLError;
  player.PlayerInfo createPlayer (String name, int phone, String password, int calory_burned_total, int steps_taken, int exp, int weight, int monster_money, String email);
} // interface PlayerOperations
