package player;


/**
* player/PlayerInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from player.idl
* Thursday, 21 May 2015 16:32:51 o'clock KST
*/

abstract public class PlayerInfoHelper
{
  private static String  _id = "IDL:player/PlayerInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, player.PlayerInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static player.PlayerInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [9];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "password",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "phone",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "calory_burned_total",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "steps_taken",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "exp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[6] = new org.omg.CORBA.StructMember (
            "weight",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[7] = new org.omg.CORBA.StructMember (
            "monster_money",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "email",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (player.PlayerInfoHelper.id (), "PlayerInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static player.PlayerInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    player.PlayerInfo value = new player.PlayerInfo ();
    value.name = istream.read_wstring ();
    value.password = istream.read_wstring ();
    value.phone = istream.read_long ();
    value.calory_burned_total = istream.read_long ();
    value.steps_taken = istream.read_long ();
    value.exp = istream.read_long ();
    value.weight = istream.read_long ();
    value.monster_money = istream.read_long ();
    value.email = istream.read_wstring ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, player.PlayerInfo value)
  {
    ostream.write_wstring (value.name);
    ostream.write_wstring (value.password);
    ostream.write_long (value.phone);
    ostream.write_long (value.calory_burned_total);
    ostream.write_long (value.steps_taken);
    ostream.write_long (value.exp);
    ostream.write_long (value.weight);
    ostream.write_long (value.monster_money);
    ostream.write_wstring (value.email);
  }

}
