package monster;


/**
* monster/MonsterInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monster.idl
* Thursday, 21 May 2015 16:44:47 o'clock KST
*/

public final class MonsterInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public int id = (int)0;
  public boolean owned = false;
  public String img = null;
  public int value = (int)0;
  public int player_id = (int)0;

  public MonsterInfo ()
  {
  } // ctor

  public MonsterInfo (String _name, int _id, boolean _owned, String _img, int _value, int _player_id)
  {
    name = _name;
    id = _id;
    owned = _owned;
    img = _img;
    value = _value;
    player_id = _player_id;
  } // ctor

} // class MonsterInfo
