package monster;


/**
* monster/MonsterHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monster.idl
* Thursday, 21 May 2015 16:44:47 o'clock KST
*/

abstract public class MonsterHelper
{
  private static String  _id = "IDL:monster/Monster:1.0";

  public static void insert (org.omg.CORBA.Any a, monster.Monster that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static monster.Monster extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (monster.MonsterHelper.id (), "Monster");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static monster.Monster read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MonsterStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, monster.Monster value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static monster.Monster narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof monster.Monster)
      return (monster.Monster)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      monster._MonsterStub stub = new monster._MonsterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static monster.Monster unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof monster.Monster)
      return (monster.Monster)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      monster._MonsterStub stub = new monster._MonsterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
