package monster;

/**
* monster/MonsterInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monster.idl
* Thursday, 21 May 2015 16:44:47 o'clock KST
*/

public final class MonsterInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public monster.MonsterInfo value = null;

  public MonsterInfoHolder ()
  {
  }

  public MonsterInfoHolder (monster.MonsterInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = monster.MonsterInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    monster.MonsterInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return monster.MonsterInfoHelper.type ();
  }

}
