package monster;

/**
* monster/MonsterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monster.idl
* Thursday, 21 May 2015 16:44:47 o'clock KST
*/

public final class MonsterHolder implements org.omg.CORBA.portable.Streamable
{
  public monster.Monster value = null;

  public MonsterHolder ()
  {
  }

  public MonsterHolder (monster.Monster initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = monster.MonsterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    monster.MonsterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return monster.MonsterHelper.type ();
  }

}
