package monster;

/**
* monster/SQLErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monster.idl
* Thursday, 21 May 2015 16:44:47 o'clock KST
*/

public final class SQLErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public monster.SQLError value = null;

  public SQLErrorHolder ()
  {
  }

  public SQLErrorHolder (monster.SQLError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = monster.SQLErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    monster.SQLErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return monster.SQLErrorHelper.type ();
  }

}
